var annotated_dup =
[
    [ "DownArrowSvg", "class_down_arrow_svg.html", "class_down_arrow_svg" ],
    [ "GpuBuffer", "class_gpu_buffer.html", "class_gpu_buffer" ],
    [ "GpuVbo", "class_gpu_vbo.html", "class_gpu_vbo" ],
    [ "HeartSvg", "class_heart_svg.html", "class_heart_svg" ],
    [ "MxAbstractSvg", "class_mx_abstract_svg.html", "class_mx_abstract_svg" ],
    [ "MxApplication", "class_mx_application.html", "class_mx_application" ],
    [ "MxClassInitializer", "struct_mx_class_initializer.html", null ],
    [ "MxColorWheelProgram", "class_mx_color_wheel_program.html", "class_mx_color_wheel_program" ],
    [ "MxList", "class_mx_list.html", "class_mx_list" ],
    [ "MxMouseEvent", "class_mx_mouse_event.html", "class_mx_mouse_event" ],
    [ "MxPainter", "class_mx_painter.html", "class_mx_painter" ],
    [ "MxPodInitializer", "struct_mx_pod_initializer.html", null ],
    [ "MxRect", "class_mx_rect.html", "class_mx_rect" ],
    [ "MxRenderer", "class_mx_renderer.html", "class_mx_renderer" ],
    [ "MxShaderProgram", "class_mx_shader_program.html", "class_mx_shader_program" ],
    [ "MxStoreAddon", "class_mx_store_addon.html", "class_mx_store_addon" ],
    [ "MxStoreView", "class_mx_store_view.html", "class_mx_store_view" ],
    [ "MxSvgPainter", "class_mx_svg_painter.html", "class_mx_svg_painter" ],
    [ "MxTextDraw", "class_mx_text_draw.html", "class_mx_text_draw" ],
    [ "MxVector", "class_mx_vector.html", "class_mx_vector" ],
    [ "MxVectorDraw", "class_mx_vector_draw.html", "class_mx_vector_draw" ],
    [ "MxVectorProgram", "class_mx_vector_program.html", "class_mx_vector_program" ],
    [ "MxWidget", "class_mx_widget.html", "class_mx_widget" ],
    [ "PlusMinusSvg", "class_plus_minus_svg.html", "class_plus_minus_svg" ],
    [ "QMewaWindow", "class_q_mewa_window.html", "class_q_mewa_window" ],
    [ "TestStoreView", "class_test_store_view.html", "class_test_store_view" ],
    [ "TestWindow", "class_test_window.html", "class_test_window" ]
];